apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pie-ingress
  namespace: pie
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: pie.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pie-api
                port:
                  number: 80

    - host: api.passengerimpact.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pie-api
                port:
                  number: 80
